---

- name: Login
  include: login.yml

- name: Remove domain from EPG
  uri:
   url: https://{{ inventory_hostname }}/api/node/mo/uni/tn-{{ item.tenant }}/ap-{{ item.app_prof }}/epg-{{ item.epg }}.json
   body: {"fvAEPg":{"attributes":{"dn":"uni/tn-{{ item.tenant }}/ap-{{ item.app_prof }}/epg-{{ item.epg }}","status":"modified"},"children":[{"fvRsDomAtt":{"attributes":{"dn":"uni/tn-{{ item.tenant }}/ap-{{ item.app_prof }}/epg-{{ item.epg }}/rsdomAtt-[uni/phys-{{ item.domain }}]","status":"deleted"},"children":[]}}]}}
   method: POST
   body_format: json
   return_content: yes
   validate_certs: False
   headers:
      Cookie: "{{ login.set_cookie }}"
  loop: "{{ epg_domain }}"


