---

- name: Login
  include: login.yml

- name: Add domain to EPG
  uri:
   url: https://{{ inventory_hostname }}/api/node/mo/uni/tn-{{ item.tenant }}/ap-{{ item.app_prof }}/epg-{{ item.epg }}.json
   body: {"fvRsDomAtt":{"attributes":{"resImedcy":"{{ item.res }}","tDn":"uni/phys-{{ item.domain }}","status":"created"},"children":[]}}
   method: POST
   body_format: json
   return_content: yes
   validate_certs: False
   headers:
      Cookie: "{{ login.set_cookie }}"
  loop: "{{ epg_domain }}"

