---

- name: Login
  include: login.yml

- name: Add Ports to FEX Interface Selector - Access
  uri:
   url: https://{{ inventory_hostname }}/api/node/mo/uni/infra/fexprof-{{ item.fexIntProfile }}/hports-{{ item.name }}-typ-range/portblk-{{ item.block }}.json
   body: {"infraPortBlk":{"attributes":{"dn":"uni/infra/fexprof-{{ item.fexIntProfile }}/hports-{{ item.name }}-typ-range/portblk-{{ item.block }}","descr":"{{ item.port_description }}","fromPort":"{{ item.from }}","toPort":"{{ item.to }}","rn":"portblk-{{ item.block }}","status":"created,modified"},"children":[]}}
   method: POST
   body_format: json
   return_content: yes
   validate_certs: False
   headers:
      Cookie: "{{login.set_cookie}}"
  loop: "{{ fex_interface_selector }}"

  
