---

- name: Login
  include: login.yml

- name: Create Switch Profile for the Leaf Switches 
  uri:
   url: https://{{ inventory_hostname }}/api/node/mo/uni/infra/nprof-{{ item.name }}.json
   body: {"infraNodeP":{"attributes":{"dn":"uni/infra/nprof-{{ item.name }}","name":"{{ item.name }}","rn":"nprof-{{ item.name }}","status":"created,modified"},"children":[{"infraLeafS":{"attributes":{"dn":"uni/infra/nprof-{{ item.name }}/leaves-{{ item.leaf_sel }}-typ-range","type":"range","name":"{{ item.leaf_sel }}","rn":"leaves-{{ item.leaf_sel }}-typ-range","status":"created,modified"},"children":[{"infraNodeBlk":{"attributes":{"dn":"uni/infra/nprof-{{ item.name }}/leaves-{{ item.leaf_sel }}-typ-range/nodeblk-{{ item.block }}","from_":"{{ item.node_id }}","to_":"{{ item.node_id }}","name":"{{ item.block }}","rn":"nodeblk-{{ item.block }}","status":"created,modified"},"children":[]}},{"infraRsAccNodePGrp":{"attributes":{"tDn":"uni/infra/funcprof/accnodepgrp-{{ item.pol_group }}","status":"created,modified"},"children":[]}}]}}]}}
   method: POST
   validate_certs: False
   body_format: json
   return_content: yes
   headers:
      Cookie: "{{ login.set_cookie }}"
  ignore_errors: yes
  loop: "{{ sw_profile }}"
