---
- name: create interface policy-group
  import_tasks: implement.yml
  when: change_state == "implement"
- name: remove interface policy-group
  import_tasks: backout.yml
  when: change_state == "backout" 
