---

- name: Login
  include: login.yml

- name: Delete vPC
  uri:
   url: https://{{ inventory_hostname }}/api/node/mo/uni/fabric/protpol.json
   body: {"fabricProtPol":{"attributes":{"dn":"uni/fabric/protpol","status":"modified"},"children":[{"fabricExplicitGEp":{"attributes":{"dn":"uni/fabric/protpol/expgep-{{ item.name }}","status":"deleted"},"children":[]}}]}}
   method: POST
   validate_certs: False
   body_format: json
   return_content: yes
   headers:
      Cookie: "{{ login.set_cookie }}"
  ignore_errors: yes
  loop: "{{ vpc }}"

