---
- name: create static port mapping for epg - fex
  import_tasks: implement.yml
  when: change_state == "implement"
- name: remove static port mappings from epg - fex
  import_tasks: backout.yml
  when: change_state == "backout" 
