---

- name: Login
  include: login.yml

- name: Delete Filter from Contract
  uri:
   url: https://{{ inventory_hostname }}/api/node/mo/uni/tn-{{ item.tenant }}/brc-{{ item.c_name }}/subj-{{ item.sub_name }}.json
   body: {"vzSubj":{"attributes":{"dn":"uni/tn-{{ item.tenant }}/brc-{{ item.c_name }}/subj-{{ item.sub_name }}","status":"modified"},"children":[{"vzRsSubjFiltAtt":{"attributes":{"dn":"uni/tn-{{ item.tenant }}/brc-{{ item.c_name }}/subj-{{ item.sub_name }}/rssubjFiltAtt-{{ item.filter }}","status":"deleted"},"children":[]}}]}}
   method: POST
   body_format: json
   return_content: yes
   validate_certs: False
   headers:
      Cookie: "{{ login.set_cookie }}"
  loop: "{{ contract }}"


