---

- name: Login
  include: login.yml

- name: Create Contract
  uri:
   url: https://{{ inventory_hostname }}/api/node/mo/uni/tn-{{ item.tenant }}/brc-{{ item.c_name }}.json
   body: {"vzBrCP":{"attributes":{"dn":"uni/tn-{{ item.tenant }}/brc-{{ item.c_name }}","name":"{{ item.c_name }}","scope":"tenant","descr":"{{ item.c_desc }} description","rn":"brc-{{ item.c_name }}","status":"created,modified"},"children":[]}}
   method: POST
   body_format: json
   return_content: yes
   validate_certs: False
   headers:
      Cookie: "{{ login.set_cookie }}"
  loop: "{{ contract }}"


