---

- name: Login
  include: login.yml

- name: Create Contract Subject
  uri:
   url: https://{{ inventory_hostname }}/api/node/mo/uni/tn-{{ item.tenant }}/brc-{{ item.c_name }}/subj-{{ item.sub_name }}.json
   body: {"vzSubj":{"attributes":{"dn":"uni/tn-{{ item.tenant }}/brc-{{ item.c_name }}/subj-{{ item.sub_name }}","name":"{{ item.sub_name }}","descr":"{{ item.sub_desc }}","rn":"subj-{{ item.sub_name }}","status":"created,modified"},"children":[]}}
   method: POST
   body_format: json
   return_content: yes
   validate_certs: False
   headers:
      Cookie: "{{ login.set_cookie }}"
  loop: "{{ contract }}"


