---

- name: Login
  include: login.yml

- name: Delete EPG
  uri:
   url: https://{{ inventory_hostname }}/api/node/mo/uni/tn-{{ item.tenant }}/ap-{{ item.app_prof }}.json
   body: {"fvAp":{"attributes":{"dn":"uni/tn-{{ item.tenant }}/ap-{{ item.app_prof }}","status":"modified"},"children":[{"fvAEPg":{"attributes":{"dn":"uni/tn-{{ item.tenant }}/ap-{{ item.app_prof }}/epg-{{ item.name }}","status":"deleted"},"children":[]}}]}}
   method: POST
   body_format: json
   return_content: yes
   validate_certs: False
   headers:
      Cookie: "{{ login.set_cookie }}"
  loop: "{{ epg }}"


