---

- name: Login
  include: login.yml

- name: Add EPG
  uri:
   url: https://{{ inventory_hostname }}/api/node/mo/uni/tn-{{ item.tenant }}/ap-{{ item.app_prof }}/epg-{{ item.name }}.json
   body: {"fvAEPg":{"attributes":{"dn":"uni/tn-{{ item.tenant }}/ap-{{ item.app_prof }}/epg-{{ item.name }}","name":"{{ item.name }}","descr":"{{ item.description }}","rn":"epg-{{ item.name }}","status":"created"},"children":[{"fvRsBd":{"attributes":{"tnFvBDName":"{{ item.bd }}","status":"created,modified"},"children":[]}}]}}
   method: POST
   body_format: json
   return_content: yes
   validate_certs: False
   headers:
      Cookie: "{{ login.set_cookie }}"
  loop: "{{ epg }}"


