---

- name: Login
  include: login.yml

- name: Access Port To Interface Backout
  uri:
   url: https://{{ inventory_hostname }}/api/node/mo/uni/infra/accportprof-{{ item.leafIntProfile }}.json
   body: {"infraAccPortP":{"attributes":{"dn":"uni/infra/accportprof-{{ item.leafIntProfile }}","status":"modified"},"children":[{"infraHPortS":{"attributes":{"dn":"uni/infra/accportprof-{{ item.leafIntProfile }}/hports-{{ item.name }}-typ-range","status":"deleted"},"children":[]}}]}}
   method: POST
   body_format: json
   return_content: yes
   validate_certs: False
   headers:
      Cookie: "{{login.set_cookie}}"
  loop: "{{ InterfaceSelector }}"
