---

- name: Login
  include: login.yml

- name: Unmap Contract from EPG
  uri:
   url: https://{{ inventory_hostname }}/api/node/mo/uni/tn-{{ item.tenant }}/ap-{{ item.app_prof }}/epg-{{ item.epg }}.json
   body: '{"fvAEPg":{"attributes":{"dn":"uni/tn-{{ item.tenant }}/ap-{{ item.app_prof }}/epg-{{ item.epg }}","status":"created,modified"},"children":[{"{{ item.method_uc }}":{"attributes":{"dn":"uni/tn-{{ item.tenant }}/ap-{{ item.app_prof }}/epg-{{ item.epg }}/{{ item.method_lc }}-{{ item.contract }}","status":"deleted"},"children":[]}}]}}'
   method: POST
   body_format: json
   return_content: yes
   validate_certs: False
   headers:
      Cookie: "{{ login.set_cookie }}"
  loop: "{{ contract_to_epg }}"


