---

- name: Login
  include: login.yml

- name: Map Contract to EPG
  uri:
   url: https://{{ inventory_hostname }}/api/node/mo/uni/tn-{{ item.tenant }}/ap-{{ item.app_prof }}/epg-{{ item.epg }}.json
   body: '{"{{ item.method_uc }}":{"attributes":{"tnVzBrCPName":"{{ item.contract }}","status":"created,modified"},"children":[]}}'
   method: POST
   body_format: json
   return_content: yes
   validate_certs: False
   headers:
      Cookie: "{{ login.set_cookie }}"
  loop: "{{ contract_to_epg }}"


