---

- name: Login
  include: login.yml

- name: Add subnet to Bridge Domain
  uri:
   url: https://{{ inventory_hostname }}/api/node/mo/uni/tn-{{ item.tenant }}/BD-{{ item.bd_name }}/subnet-[{{ item.subnet }}/{{ item.mask }}].json
   body: {"fvSubnet":{"attributes":{"dn":"uni/tn-{{ item.tenant }}/BD-{{ item.bd_name }}/subnet-[{{ item.subnet }}/{{ item.mask }}]","ctrl":"unspecified","ip":"{{ item.subnet }}/{{ item.mask }}","preferred":"true","scope":"public,shared","rn":"subnet-[{{ item.subnet }}/{{ item.mask }}]","status":"created"},"children":[]}}
   method: POST
   body_format: json
   return_content: yes
   validate_certs: False
   headers:
      Cookie: "{{ login.set_cookie }}"
  loop: "{{ bd_subnet }}"


