---

- name: Login
  include: login.yml

- name: Remove Contract Filter
  uri:
   url: https://{{ inventory_hostname }}/api/node/mo/uni/tn-{{ item.tenant }}.json
   body: {"fvTenant":{"attributes":{"dn":"uni/tn-{{ item.tenant }}","status":"modified"},"children":[{"vzFilter":{"attributes":{"dn":"uni/tn-{{ item.tenant }}/flt-{{ item.name }}","status":"deleted"},"children":[]}}]}}
   method: POST
   body_format: json
   return_content: yes
   validate_certs: False
   headers:
      Cookie: "{{ login.set_cookie }}"
  loop: "{{ filter }}"


