---

- name: Login
  include: login.yml

- name: Create Contract Filter Entry
  uri:
   url: https://{{ inventory_hostname }}/api/node/mo/uni/tn-{{ item.tenant }}/flt-{{ item.name }}/e-{{ item.entry_id }}.json
   body: {"vzEntry":{"attributes":{"dn":"uni/tn-{{ item.tenant }}/flt-{{ item.name }}/e-{{ item.entry_id }}","name":"{{ item.entry_id }}","etherT":"ip","status":"created,modified","prot":"{{ item.protocol }}","dFromPort":"{{ item.from_port }}","dToPort":"{{ item.to_port }}","rn":"e-{{ item.entry_id }}"},"children":[]}}
   method: POST
   body_format: json
   return_content: yes
   validate_certs: False
   headers:
      Cookie: "{{ login.set_cookie }}"
  loop: "{{ filter }}"


