---

- name: Login
  include: login.yml

- name: Remove Contract Filter Entry
  uri:
   url: https://{{ inventory_hostname }}/api/node/mo/uni/tn-{{ item.tenant }}/flt-{{ item.name }}.json
   body: {"vzFilter":{"attributes":{"dn":"uni/tn-{{ item.tenant }}/flt-{{ item.name }}","status":"modified"},"children":[{"vzEntry":{"attributes":{"dn":"uni/tn-{{ item.tenant }}/flt-{{ item.name }}/e-{{ item.entry_id }}","status":"deleted"},"children":[]}}]}}
   method: POST
   body_format: json
   return_content: yes
   validate_certs: False
   headers:
      Cookie: "{{ login.set_cookie }}"
  loop: "{{ filter }}"


