---
- name: create static port mapping for epg - leaf
  import_tasks: implement.yml
  when: change_state == "implement"
- name: remove static port mapping from epg - leaf
  import_tasks: backout.yml
  when: change_state == "backout" 
